### ISSUE TITLE
raspi-config bbappend typo 

### ISSUE THREAD

**Issue by SeungWoo-L** [SEA-ME-COSS/meta-infotainment#1]
There is a typo in do_deploy: append () in the Raspberry Pi config file. I think it should be changed to 1 instead of l

dtparam=spi=on
dtoverlay=spi1-3cs
dtoverlay=mcp251xfd,spi0-0,interrupt=25
dtoverlay=mcp251xfd,spi1-0,interrupt=24

[2-CH_CAN_FD_HAT](https://www.waveshare.com/wiki/2-CH_CAN_FD_HAT)

**Comment by SeungWoo-L** [comment]
Unfortunately can1 still doesn't work, any thoughts on this?

**Comment by dongdongO** [comment]
https://docs.yoctoproject.org/what-i-wish-id-known.html

Remember, all the answer is in here
